# Generated by Django 4.1.2 on 2022-10-12 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100,
                 verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='CityHood',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(
                    max_length=100, verbose_name='Название района')),
            ],
            options={
                'verbose_name': 'Район города',
                'verbose_name_plural': 'Районы города',
            },
        ),
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100,
                 verbose_name='Название предприятия')),
                ('description', models.TextField(verbose_name='Описание')),
                ('hoods', models.ManyToManyField(
                    to='spider.cityhood', verbose_name='Районы')),
            ],
            options={
                'verbose_name': 'Предприятие',
                'verbose_name_plural': 'Предприятии',
            },
        ),
        migrations.CreateModel(
            name='EnterpriseNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(
                    max_length=100, verbose_name='Название сети')),
            ],
            options={
                'verbose_name': 'Сеть предприятий',
                'verbose_name_plural': 'Сеть предприятий',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(
                    max_length=100, verbose_name='Название товара')),
                ('last_price', models.IntegerField(blank=True, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                 related_name='products', to='spider.category', verbose_name='Категория')),
                ('enterprises', models.ManyToManyField(
                    to='spider.enterprise', verbose_name='Предприятия')),
                ('network', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                 related_name='products', to='spider.enterprisenetwork', verbose_name='Сеть')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='Цена товара')),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='prices', to='spider.enterprise', verbose_name='Предприятие')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='prises', to='spider.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Цена на товар',
                'verbose_name_plural': 'Цены на товар',
            },
        ),
        migrations.AddField(
            model_name='enterprise',
            name='network',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='enterprises', to='spider.enterprisenetwork', verbose_name='Сеть'),
        ),
    ]
